# Generated by Django 2.2.6 on 2019-12-01 17:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('archivo_id', models.AutoField(primary_key=True, serialize=False)),
                ('archivo', models.CharField(max_length=200)),
                ('informePeticionario', models.CharField(max_length=200)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('carrera_id', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=150)),
                ('nombre', models.CharField(max_length=50)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('ciclo_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=3)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('docente_id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('carrera', models.CharField(max_length=50)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('materia_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('creditos', models.CharField(max_length=10)),
                ('codigo', models.CharField(max_length=50)),
                ('duracion', models.CharField(max_length=10)),
                ('obligatoria', models.CharField(max_length=10)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.Ciclo')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('periodoAcademico_id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('estado', models.BooleanField(default=True)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('persona_id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('apellidos', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=50)),
                ('edad', models.CharField(max_length=3)),
                ('fechaNacimiento', models.DateField()),
                ('direccion', models.TextField(default='sin direccion', max_length=50)),
                ('telefono', models.CharField(max_length=13)),
                ('foto', models.CharField(max_length=200)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('rol_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(choices=[('decano', 'Decano'), ('abogado', 'Abogado'), ('docente', 'Docente'), ('solicitante', 'Solicitante')], default='Solicitante', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('tramite_id', models.AutoField(primary_key=True, serialize=False)),
                ('registro', models.CharField(max_length=200)),
                ('estado', models.BooleanField(default=False)),
                ('external_docente', models.CharField(max_length=200)),
                ('external_carrera', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=200)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('archivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.Archivo')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Silabo',
            fields=[
                ('Silabo_id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True)),
                ('archivo', models.CharField(max_length=200)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.Docente')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.Materia')),
                ('periodoAcademico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.PeriodoAcademico')),
            ],
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('seguimiento_id', models.AutoField(primary_key=True, serialize=False)),
                ('revSolicitud', models.BooleanField(default=False)),
                ('revSellos', models.BooleanField(default=False)),
                ('asigDocente', models.BooleanField(default=False)),
                ('revDocumentacion', models.BooleanField(default=False)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.Tramite')),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.Rol'),
        ),
        migrations.CreateModel(
            name='MallaCurricular',
            fields=[
                ('mallaCurricular_id', models.AutoField(primary_key=True, serialize=False)),
                ('archivo', models.CharField(max_length=200)),
                ('anio', models.DateField()),
                ('estado', models.BooleanField(default=True)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.Carrera')),
            ],
        ),
        migrations.AddField(
            model_name='docente',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.Persona'),
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('cuenta_id', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=50)),
                ('clave', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.Persona')),
            ],
        ),
        migrations.AddField(
            model_name='ciclo',
            name='mallaCurricular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.MallaCurricular'),
        ),
    ]
