# Generated by Django 2.2.6 on 2019-12-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mallacurricular',
            name='anio',
            field=models.CharField(max_length=5),
        ),
    ]
